# Generated by Django 4.2.1 on 2023-05-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anfitrion',
            fields=[
                ('idAnfitrion', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=45, null=True)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('paterno', models.CharField(max_length=45, null=True)),
                ('materno', models.CharField(max_length=45, null=True)),
                ('cargo', models.CharField(max_length=45, null=True)),
                ('dependencia', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
                ('extension', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
